[github]
token = "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"
owner = "aidarpavl"
repo = "Stolovaya-zaiavka"
branch = "main"
menu_path = "menu.csv"
daily_report_path = "Stolovaia ZHD1.csv"
monthly_report_path = "Stol_Zhd month1.csv"

[auth]
chef_password = "povar2026"